TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Install scripts
PLUGINSCRIPTS += adPythonBarCode.py
PLUGINSCRIPTS += adPythonCircle.py
PLUGINSCRIPTS += adPythonCrystalDroplet.py
PLUGINSCRIPTS += adPythonCrystalFeatureMatch.py
PLUGINSCRIPTS += adPythonDataMatrix.py
PLUGINSCRIPTS += adPythonFocus.py
PLUGINSCRIPTS += adPythonGaussian2DFitter.py
PLUGINSCRIPTS += adPythonMitegen.py
PLUGINSCRIPTS += adPythonMorph.py
PLUGINSCRIPTS += adPythonMxSampleDetect.py
PLUGINSCRIPTS += adPythonPowerMean.py
PLUGINSCRIPTS += adPythonRotate.py
PLUGINSCRIPTS += adPythonTemplate.py
PLUGINSCRIPTS += adPythonTransfer.py
PLUGINSCRIPTS += transferclient.py

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
